on:
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - run: "echo Job ${{gitub.job}}"

  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - run: "echo Job ${{gitub.job}}"
  
  
  job_3:
    runs-on: ubuntu-latest
    needs: job_4
    steps:
      - run: "echo Job ${{gitub.job}}"

  job_4:
    runs-on: ubuntu-latest
    needs: [job_2, job_1]
    steps:
      - run: "echo Job ${{gitub.job}}"
