name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  ex-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print a welcome message
        run: echo "Welcom to our first Github Actions Workflow"
